---
name: Deploy to CloudFront
on:
  push:
    branches:
      - main

jobs:
  build-hugo-and-push-to-s3:
    runs-on: ubuntu-latest
    container: hugomods/hugo:ci-0.128.2
    steps:
      - uses: actions/checkout@v4
      - run : |
          ls -la .
      - run: |
          hugo && ls -la public/
      - run: |
          echo Upload these files to s3 for server
