---
name: Deploy to CloudFront
on:
  push:
    branches:
      - main

jobs:
  build-hugo-and-push-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-dept: 0
      - name: Install Hugo on Ubuntu
        run: |
          sudo apt install -y hugo
      - name: Generate Static Files
        run: |
          hugo && ls -la public/
      - name: Upload the files to S3 Bucket
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'public'
