---
name: Deploy to CloudFront
on:
  push:
    branches:
      - main

jobs:
  build-hugo-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-dept: 0
      - name: Install Hugo and AWS CLI on Ubuntu
        run: |
          sudo apt update
          sudo apt install -y hugo
          sudo snap install aws-cli --classic
      - name: Generate Static Files
        run: |
          hugo && ls -la public/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Upload files
        env:
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: |
          aws s3 mv public/* s3://$AWS_BUCKET/ --recursive

